// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLsczSIcw4i34yMCBZulqsn6d9Nm6ln4A',
    appId: '1:678917337930:web:d9698c265ea73683dcc7b3',
    messagingSenderId: '678917337930',
    projectId: 'csi-app-5d154',
    authDomain: 'csi-app-5d154.firebaseapp.com',
    storageBucket: 'csi-app-5d154.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_qocFalokw5Z0-LoTgrt_u7z9bQpih-0',
    appId: '1:678917337930:android:e67b69a03d7ce7cbdcc7b3',
    messagingSenderId: '678917337930',
    projectId: 'csi-app-5d154',
    storageBucket: 'csi-app-5d154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2aaYLhkvIvbpsyBFjyaFxpkDjHqgd8qU',
    appId: '1:678917337930:ios:227ecb27b4d4f6c8dcc7b3',
    messagingSenderId: '678917337930',
    projectId: 'csi-app-5d154',
    storageBucket: 'csi-app-5d154.appspot.com',
    iosBundleId: 'com.example.csi',
  );
}
